name: Auto Tag on Commit

on:
  push:
    branches:
      - QA      

jobs:
  build_no_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}
      - name: Use Another Repo
        uses: netxd-test/QA_Repo/.github/workflows@main
        with:
          Bot-Token: ${{ secrets.BOT_TOKEN }} 
      - name: check
        run: |
            echo "repository variable : $REPOSITORY_VAR"
        env:
           env_var: ${{ vars.WORKFLOW_PATH }}