name: Auto Tag on Commit

on:
  push:
    branches:
      - QA

jobs:
  build_no_release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'MINOR_RELEASE') && !contains(github.event.head_commit.message, 'MAJOR_RELEASE') }}
    
    strategy:
      matrix:
        repository:
          - QA_Repo

         

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: ${{ secrets.BOT_TOKEN }}
          repository: ${{ matrix.repository }}