name: Auto Tag on Commit

on:
  push:
    branches:
      - QA

jobs:
  build_no_release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'MINOR_RELEASE') && !contains(github.event.head_commit.message, 'MAJOR_RELEASE') }}
    steps:
      - name: Include QA Tags Workflow from Shared Repository
        uses: netxd-test/QA_Repo/.github/workflows/action.yml@main
        with:
          Bot-Token: ${{ secrets.BOT_TOKEN }}

      