name: Auto Tag on Commit

on:
  push:
    branches:
      - QA      

jobs:
  build_no_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}

      - name: Determine Action to Use
        run: echo "::set-output name=action::$env_var"
        env:
          env_var: ${{ vars.WORKFLOW_PATH }}
        id: determine_action          
          
      - name: Use Another Repo
        uses: ${{ steps.determine_action.outputs.action }}
        with:
          Bot-Token: ${{ secrets.BOT_TOKEN }} 
        